jwt:
  secretKey: dfnjdfkuegfndcedijgcuiedhciledhcjhdekljchkdejhckjdhcjkdghc
  
spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                isEnabled: false
          
        - id: inventory-service
          uri: http://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-CUSTOM_HEADER, Nupur
            - name: Authentication
