spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2

        - id: inventory-service
          uri: http://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
