server.servlet.context-path=/orders
server.port=9020

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_SERVICE:order-service}:5432/${DB_NAME:orderdb}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
